### ISSUE TITLE
Segmetation fault in SleepyDiscord::CustomSession::setUrl

### ISSUE THREAD

**Issue by TheFinnishArmy** [yourWaifu/sleepy-discord#105]
Tried running the rock-paper-scissors on Ubuntu 18.04. The program immediately halts to a segmentation fault from setUrl. Using Websocket++ if that's of any help.

Output from gdb:
![ubuntu1804_2018-07-30_22-39-41](https://user-images.githubusercontent.com/22451500/43419425-8026661c-9449-11e8-909c-ce2fe82354a5.png)

**Comment by yourWaifu** [comment]
Did you set ``SleepyDiscord::CustomSession::init``?

**Comment by TheFinnishArmy** [comment]
Set where? Sorry, my English is not the sharpest, but I didn't notice any part in the basic "How to" documents about setting it...

**Comment by yourWaifu** [comment]
CustomSession hasn't been documented. But, from looking at the situation, it looks like you are confused. Right now, you don't have a HTTP library so Sleepy Discord uses CustomSession. However, the rock-paper-scissors example needs a HTTP library in order to function. To fix this, you'll need to add a HTTP library to Sleepy Discord. I recommend you use the set up script and download cpr and compile it by doing
```
sudo apt-get install libcurl4-openssl-dev
cd sleepy_discord/deps/cpr
g++ -c cpr/*.cpp -I ../include
ar rv libcpr.a *.o
mv libcpr.a ../lib
```
and then when you go to compile rock-paper-scissors, remember to add ``-L deps/lib``-lcpr`` and ``-lcurl``.

**Comment by TheFinnishArmy** [comment]
Thank you, couldn't have figured it out without your help tbh. 👍
