### ISSUE TITLE
adding "SLEEPY_USE_HARD_CODED_GATEWAY" causes errors while compiling

### ISSUE THREAD

**Issue by dedady157** [yourWaifu/sleepy-discord#128]
so i added "add_definitions  (-DSLEEPY_USE_HARD_CODED_GATEWAY)" to my cmake files, because i was having issues to were i had to fully recreate the build folder every time in order to use the bot, otherwise i would get error 5002 and 5003, but in doing this it creates an error

```
/Services/Code/BlackBot/sleepy-discord/sleepy_discord/client.cpp: In member function ‘void SleepyDiscord::BaseDiscordClient::getTheGateway()’:
/Services/Code/BlackBot/sleepy-discord/sleepy_discord/client.cpp:188:63: error: cannot convert ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘char*’ for argument ‘1’ to ‘char* strncpy(char*, const char*, size_t’
   std::strncpy(theGateway, "wss://gateway.discord.gg/?v=6", 32); //This is needed for when session is disabled
                                                               ^
sleepy-discord/sleepy_discord/CMakeFiles/sleepy-discord.dir/build.make:134: recipe for target 'sleepy-discord/sleepy_discord/CMakeFiles/sleepy-discord.dir/client.cpp.o' failed
make[2]: *** [sleepy-discord/sleepy_discord/CMakeFiles/sleepy-discord.dir/client.cpp.o] Error 1
```

**Comment by dedady157** [comment]
i make a quick fix,
Infile ./sleepy_discord/client.cpp lines (189-191)
```c++
#ifdef SLEEPY_USE_HARD_CODED_GATEWAY
		theGateway = theGateway + "wss://gateway.discord.gg/?v=6";	//This is needed for when session is disabled
#else
```

**Comment by dedady157** [comment]
some more debugging and the problem is with how it gets web data

**Comment by yourWaifu** [comment]
The above code you just posted and SLEEPY_USE_HARD_CODED_GATEWAY doesn't fix the errors you posted. The errors will pop up again when using any http request. It's better that errors stopping you from getting the gateway url are fixed.

**Comment by dedady157** [comment]
its odd tho, i was working and then it started to not work, the problem is how its getting web data, because the request all ways returns an empty responce

**Comment by yourWaifu** [comment]
I can't exactly remember but I remember this error is caused by an CURLE_PEER_FAILED_VERIFICATION error in libcurl.
For some reason, deleting the cmake cache fixes this issue. I don't know why.
You can also fix this with those lines of code
```
//Warning: security risk, man in the middle
curl_setopt ($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, 0); 
```
But it's not a good idea since it's a creates a security risk.
You could also make modifications to the CPR library to make it use [CA certificates from here](https://curl.haxx.se/docs/caextract.html) by adding those lines of code to where CPR sets up the http request with libcurl.
```
curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, TRUE); 
curl_setopt ($ch, CURLOPT_CAINFO, "pathto/cacert.pem");
```
For information can be found here http://ademar.name/blog/2006/04/curl-ssl-certificate-problem-v.html
I also know that issue doesn't pop up when compiling without cmake, so I've been investigating why that's the case.

**Comment by dedady157** [comment]
adding

InFile ./sleepy-discord/deps/cpr/cpr/session.cpp
    InFunc: "Session::Impl::Impl()"
```
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0); 
curl_easy_setopt(curl, CURLOPT_CAINFO, "pathto/cacert.pem");
```

makes it work all the time now
