### ISSUE TITLE
Getting exception on sending Cyrillic text

### ISSUE THREAD

**Issue by Paket236** [yourWaifu/sleepy-discord#135]
Hi! Sorry for my English.
1. The library crashes when I send Cyrillic text.
```
sendMessage(message.channelID, "йцукен");
```
In addition, the library does not detect Cyrillic text.
```
if (message.startsWith("фывапр")) {
	sendMessage(message.channelID, "asd");
}
```
Is it possible to fix it and when can you do it?

2. How can I get a list of all users on the server?

**Comment by Paket236** [comment]
Same problem with
```
sendMessage(message.channelID, "\n");
```

**Comment by yourWaifu** [comment]
1. please read the note https://yourwaifu.github.io/sleepy-discord/documentation.html#sendmessage
As for Cyrillic text or any unicode symbol, use javascript's JSON unicode encoding. For example, the unicode system й is U+0439 so you use ``\\u0439``. More info can be found here https://www.json.org/. The reason this is the case, is because the Discord API sends and recevices data using json. There's also one but that's not a topic related to this issue. So all strings going to and from Sleepy Discord need to be a JSON string.

2.
```cpp
//serverObject is a SleepyDiscord::Server with server data.
for (serverObject.members : SleepyDiscord::ServerMember& member) {
    std::cout << "Name: " << member.user.name << "Nickname" << member.nick;
}
//This print the name and nickname of all members in a server.
```

**Comment by yourWaifu** [comment]
In the future I might add a new function that might let more easily convert a UTF-8 encoded string literal like the one that you are using into a json string. For the develop version I might be able to do that if the rapidjson library has one, but for the master version, there's a unicode converter but it's old and hasn't been used for a long time so that'll need to be updated.

**Comment by yourWaifu** [comment]
Actually, nevermind it works on my end. I'm currently on vacation and only have access to the development version Sleepy Discord. However the develop version Sleepy Discord does things very differently so something in the develop version fixes this.

**Comment by Paket236** [comment]
Thanks for answers. You helped me a lot.
Now I have 2 new questions.
1. How to get a list of all users _at the moment_? I can get the starting list in the
`void onServer(SleepyDiscord::Server)`
function, but since then the user can log out or log in, so I need an up-to-date list (for example, inside the `void onMessage(SleepyDiscord::Message) { }` function when an event occurs).
2. How can I send a message to a specific text channel? Suppose I manually created a webhook in discord and got a url, what do I need to do now in the code?

**Comment by Paket236** [comment]
2. On this point, I figured out. I need to use the `executeWebhook()` function

**Comment by yourWaifu** [comment]
There are a few ways of doing this. So I'll give you a few options that I know of.

option 1: Discord is always sending you server update info so you can use that to update your list of servers that you stored. The problem is the current master version doesn't handle updates very well compared to the develop version. However, thankfully you are just looking when a user joins. You can use these 3 events 
```cpp
virtual void onMember            (std::string* jsonMessage);
virtual void onRemoveMember      (std::string* jsonMessage);
virtual void onEditMember        (std::string* jsonMessage);
```
I recomemd you take a look at the develop version's code on to convert those string pointers into something usable. https://github.com/yourWaifu/sleepy-discord/blob/ac62cfed4c3d2d1101f3c625cfe4a41a19a07a76/include/sleepy_discord/client.h#L312
https://github.com/yourWaifu/sleepy-discord/blob/ac62cfed4c3d2d1101f3c625cfe4a41a19a07a76/sleepy_discord/client.cpp#L417

option 2:
```cpp
//get the server from Discord
client.getServer(serverID);
```
This is really simple but it has a lot of downsides you should be aware of. Since this sends a request to Discord it's speed depends on your internet connection. It's also a waste since Discord already sent you most of the server data at the begining and sending you updates. If you pay your cloud service's bandwidth, then you are paying for data that you already have or something like that. However, I'm not going to lie it's super simple in comparison.

**Comment by AlexandrSMed** [comment]
>    As for Cyrillic text or any unicode symbol, use javascript or JSON unicode encoding. For example, the unicode system й is U+0439 so you use `\\u0439`. More info can be found here https://www.json.org/. The reason this is the case, is because the Discord API sends and recevices data using json. There's also one other encoding but that's not a topic related to this issue. So all strings going to and from Sleepy Discord need to be a JSON string.

As far as I understand this doesn't currently work because the stringified content is processed by rapidjson lib and has all special symbols wrapped with backslashes. Is there any workaround but using u8 strings? I need to have it C++20 compatible somehow

**Comment by yourWaifu** [comment]
@AlexandrSMed I have wrote about this here https://yourwaifu.dev/sleepy-discord/docs/unicode

**Comment by AlexandrSMed** [comment]
@yourWaifu I might be missing something but I can't see how it makes the things different. Unicode code points inside of C++ strings are equivalent of a corresponding character and treated the same way so I getting pretty much the same result (a runtime exception) for both invocations:
```
sendMessage(channelID, "й");
```
and
```
sendMessage(channelID, "\u0439");
```
As you suggested earlier we actually should want to pass Unicode code point as a string literal to Discord API (like "\\u0439") but that's impossible to do via SleepyDiscord API because the content string get escaped by rapidjson under the hood, so we get something like "\\\u0439" in the json parameter and "\u0439" in the discord app in the end, not the "й" symbol

**Comment by yourWaifu** [comment]
@AlexandrSMed You're forgetting the u8 part which is pretty important.

**Comment by AlexandrSMed** [comment]
@yourWaifu I'm afraid this part of my question was overlooked:
> Is there any workaround but using u8 strings? I need to have it C++20 compatible somehow

**Comment by yourWaifu** [comment]
@AlexandrSMed the fact above hasn't changed, that one thing that has changed is chat8_t. This means you are required to do a cast. From what I'm aware the conversation can only be done at runtime via a copy. I haven't used C++20 yet but maybe a bit cast will work or maybe even a reinterpretate cast. It's a mess to be honest and I'm not sure what the people writing the standards were thinking.
