### ISSUE TITLE
Debian cmake

### ISSUE THREAD

**Issue by NotAefka** [yourWaifu/sleepy-discord#139]
When I use cmake on debian I get this : 
`CMake Error at sleepy_discord/CMakeLists.txt:41 (target_compile_features):
  target_compile_features specified unknown feature "cxx_std_14" for target
  "sleepy-discord".`
Please help me...

**Comment by Rasikh-Qadeer** [comment]
How did you fix this issue @NotAefka

**Comment by yourWaifu** [comment]
@Rasikh-Qadeer There are a few ways you can fix this. The problem is that Debian gives you an outdated version of cmake that's missing cxx_std_14.

You can fix this by downloading and compiling the source from https://cmake.org/download/ or https://github.com/Kitware/CMake/releases and follow [the instructions in the readme](https://github.com/Kitware/CMake#unixmac-osxmingwmsyscygwin).

You may also instead replace the line giving the error with:
```cmake
set(CMAKE_CXX_STANDARD 14)
```

**Comment by Rasikh-Qadeer** [comment]
Thank you, built CMake from source and successfully built Sleepy-Discord
